### ISSUE TITLE
Admin-addon installation in eclipse

### ISSUE THREAD

**Issue by vbini21** [adminfaces/admin-addon#4]
How do you access "Install Addon from the catalog[current selection: /admin-addon], where you then select "Adminfaces addon" from the list. 
I tried installing using eclipse "Install new software" and provided the link _https://github.com/adminfaces/admin-addon.git_ but the reply is "could not find https://github.com/adminfaces/admin-addon.git"

I downloaded the admin-addon-master project, opened it in eclipse and downloaded the dependencies too. Where could I be going wrong with this process?

**Comment by rmpestano** [comment]
Hello, you need to first install [jboss-forge](https://forge.jboss.org/) eclipse plugin (It comes in jboss tools plugin), and then use addon-install command and provide the adminfaces addon github url

**Comment by vbini21** [comment]
Hi, I have done so as advised, when I try to install the addon from the catalog or from GIT i get the error below: 
Unable to execute project build.
I have tried this using eclipse both on linux and windows. I can build other programs successfully.

**Comment by vbini21** [comment]
From the Error logs:

Problems occurred when invoking code from plug-in: "org.eclipse.jst.jee".
java.lang.NullPointerException
	at org.eclipse.jst.jee.model.internal.JEE5ModelProvider.createModelResource(JEE5ModelProvider.java:209)
	at org.eclipse.jst.jee.model.internal.JEE5ModelProvider.getModelResource(JEE5ModelProvider.java:190)
	at org.eclipse.jst.jee.model.internal.Web25ModelProvider.getModelObject(Web25ModelProvider.java:44)

**Comment by vbini21** [comment]
[eclipse-workspace]$ addon-install-from-git --url https://github.com/adminfaces/admin-addon.git
***INFO*** Installing Addon from Git 	[1/4] ...
***INFO*** Installing Addon from Git:Cloning repository in /tmp/tmpdir7805428912945439723 	[1/4] ...
***INFO*** Installing Addon from Git:Installing project into local repository 	[2/4] ...
***ERROR*** Error while executing 'addon-install-from-git'
org.jboss.forge.addon.projects.building.BuildException: Build failed.
	at org.jboss.forge.addon.maven.projects.MavenProjectBuilder.build(MavenProjectBuilder.java:118)
	at org.jboss.forge.addon.manager.impl.ui.AddonGitBuildAndInstallCommand.execute(AddonGitBuildAndInstallCommand.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at org.jboss.forge.addon.manager.impl.ui.AddonGitBuildAndInstallCommand_$$_jvstfa_4f.execute(AddonGitBuildAndInstallCommand_$$_jvstfa_4f.java)
	at org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.execute(SingleCommandControllerImpl.java:94)
	at org.jboss.forge.addon.shell.aesh.CommandAdapter.execute(CommandAdapter.java:97)
	at org.jboss.forge.addon.shell.aesh.ForgeCommandContainer.executeCommand(ForgeCommandContainer.java:88)
	at org.jboss.aesh.console.AeshConsoleImpl$AeshConsoleCallbackImpl.execute(AeshConsoleImpl.java:311)
	at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
***ERROR*** Unable to execute project build
[eclipse-workspace]$

**Comment by vbini21** [comment]
I realized after thorough reseach that red hat jboss developer studio already has the adminfaces addon installed. In combination with open jdk from redhat too the error above goes away.

**Comment by vbini21** [comment]
Attached is a copy of the error logs

[error log.txt](https://github.com/adminfaces/admin-addon/files/5683689/error.log.txt)

**Comment by rmpestano** [comment]
Hi @vbini21,

```
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to transfer org.jboss.forge.furnace.container:simple:pom:2.28.1.Final from http://repo1.maven.org/maven2 was cached in the local 
``` 

Looks like you have a corrupted artefacts on you local maven repository or you have issues reaching maven central. Try deleting your local .m2 and try building again. 

Are you behind a corporate proxy? That can also be an issue and you have to configure maven settings accordingly

**Comment by vbini21** [comment]
@rmpestano , thanks. The error above emanated from the maven settings configuration. Maven has to be accessed via https so i added the code below in the `<profiles>` section and the admin-addon installed successfully.

`<profile>
    <id>maven-https</id>
    <activation>
        <activeByDefault>true</activeByDefault>
    </activation>
    <repositories>
        <repository>
            <id>central</id>
            <url>https://repo1.maven.org/maven2</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>central</id>
            <url>https://repo1.maven.org/maven2</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
</profile>`

**Comment by vbini21** [comment]
I get this error after executing scaffold generation.
`Caused by: org.yaml.snakeyaml.error.YAMLException: Class not found: com.github.adminfaces.addon.scaffold.model.GlobalConfig`
The previous steps have been a success following the admin-addon guide [.](https://github.com/adminfaces/admin-addon)
I have tried adding the code below in the pom.xml with no success. 
`<dependency>
      <groupId>com.github.adminfaces.addon</groupId>
      <artifactId>admin-addon</artifactId>
      <version>1.0.0</version>
    </dependency>`
Attached is a copy of the full Stack Trace.
[stacktrace.txt](https://github.com/adminfaces/admin-addon/files/5691685/stacktrace.txt)

**Comment by rmpestano** [comment]
Hi @vbini21, I just tried the command in a fresh eclipse instance and its working here:
 
![admin-scaffold](https://user-images.githubusercontent.com/1592273/102687553-9abbcf00-41ce-11eb-965f-8c93f7f3a526.png)


my eclipse installation is:

```
Red Hat Developer Studio

Version: 12.9.0.GA
```
and it comes with jboss forge 3.9.1

Can you try to clean `.forge` dir located on your operating system home and then restart forge and install admin-addon again?


If it still fails then I will need a sample project where the scaffold command is failling so I can debug the plugin

**Comment by vbini21** [comment]
After following the maven settings guide it has worked, i think all the issues emanated from maven settings on my side.
Thank you.

**Comment by rmpestano** [comment]
Glad to hear @vbini21!

Do you know which specific setting was causing the issue?

**Comment by vbini21** [comment]
Thanks @rmpestano 
Initially the user settings.xml only had the path to local repository i.e in the .m2 folder. From the Jboss Developer Studio guidelines the setting.xml should be set to be as in the attachment below.
[settings.txt](https://github.com/adminfaces/admin-addon/files/5730798/settings.txt)

**Comment by vbini21** [comment]
@rmpestano, could you be having a guide on how to host the generated scaffold online,a document or a link that i would follow to do that.

**Comment by rmpestano** [comment]
> how to host the generated scaffold online

What do you mean?

**Comment by vbini21** [comment]
After generating a website that runs on wildfly locally, hosting it now 'Online', I meant not locally on my machine but on remote servers eg. openshift, amazon etc

**Comment by rmpestano** [comment]
It should be the same for any other web application which spin up a server in a specific port. You should search the documention for each cloud provider you may want to run.

One thing that may make things easier for you is that generated code has also scripts to run It as a docker container which most cloud providers support. On this vídeo the generated app runs as docker container: https://youtu.be/_uZXXnvJp_E

I Hope It helps

**Comment by vbini21** [comment]
Yea it does, thanks.

**Comment by vbini21** [comment]
Am getting this error clicking on any menu i.e rooms, speakers or talks.
`java.lang.NoSuchMethodError: org.primefaces.model.SortMeta.<init>(Ljava/lang/String;Ljava/lang/String;Lorg/primefaces/model/SortOrder;Ljavax/el/MethodExpression;)V`
 Previously the build process is successful and the project runs on docker after bash build-and-run command.

**Comment by rmpestano** [comment]
Did you updated PrimeFaces to `8.0`?

**Comment by vbini21** [comment]
@rmpestano thanks, it worked. A few elements are not responsive such as the switch button. I have noted a few warnings such as 
`Unable to find or serve resource, fonts/source-sans-pro-v11-latin-italic.woff2, from library, admin-lte.
15:11:13,093 WARNING [javax.enterprise.resource.webcontainer.jsf.application] (default task-3) : java.io.IOException: Broken pipe
`

**Comment by vbini21** [comment]
@rmpestano thanks. It worked after updating primefaces

**Comment by vbini21** [comment]
I have been generating scaffolds successfully. Any time i add a field to the project after scaffold generation for the first time i get this error. 
`FTL stack trace ("~" means nesting-related):
	- Failed at: #if entity.isRequired(field) && !fiel...  [in template "scaffold/freemarker/list.xhtml" at line 80, column 261]`

**Comment by rmpestano** [comment]
Yea, you need to compile the project after adding new entity fields or use [automatic build option](https://www.benchresources.net/how-to-build-java-project-in-eclipse-ide-automatically/)
